### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by BPScott** [bbc/ipr-php-cache#1]
Whatever happened to https://github.com/bbc/rmp-php-cache-lib?

**Comment by alexgisby** [comment]
@BPScott This is a fork of the original with several breaking changes including a namespace rename to make it appropriate to release publicly. The majority of people are using this at dev-master rather than a pinned version, so a composer update would break them. Hence the repo move and the composer package name change.

**Comment by BPScott** [comment]
Groovy groovy, so the aim is to stop people using and eventually delete rmp-php-cache-lib?

Taking a nose at https://github.com/search?q=bbc-rmp%2Fcache&type=Code&utf8=✓, radio-nav-service and rmp-radio-nhp-service are the only two relevant consumers that appear, are there many other dependencies that are hiding?
